//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WagharalkarMVCProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDoctor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public string Education { get; set; }
        public string InstaGramLink { get; set; }
        public string FacebookLink { get; set; }
        public string LinkedInLink { get; set; }
    }
}
